/**
 * Regenerates sitemap.xml from all root-level *.html files (excluding nav.html).
 * Run from repo root: node scripts/generate-sitemap.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const BASE = 'https://www.casadecoronacabo.com';

/** Destination / guide pages (priority 0.8) */
const DESTINATION_SLUGS = new Set([
  'cabo-san-lucas',
  'medano-beach',
  'cabo-marina',
  'chileno-bay',
  'palmilla-beach',
  'san-jose-del-cabo',
  'cabo-pulmo',
  'todos-santos',
  'cerritos-beach',
  'la-paz',
  'balandra-beach',
  'el-tecolote-beach',
]);

/** Property / booking SEO landing pages (priority 0.75) */
const SEO_LANDING_SLUGS = new Set([
  'cabo-san-lucas-vacation-rental',
  'short-term-rental-cabo-san-lucas',
  'family-vacation-rental-cabo-san-lucas',
  'ocean-view-vacation-rental-cabo',
  'el-tezal-vacation-rental',
  'direct-booking-cabo-san-lucas',
  'condo-rental-cabo-san-lucas',
  'vacation-rental-near-medano-beach',
]);

function priorityForSlug(slug) {
  if (slug === '') return { priority: '1.0', changefreq: 'weekly' };
  if (slug === 'what-to-do') return { priority: '0.9', changefreq: 'weekly' };
  if (SEO_LANDING_SLUGS.has(slug)) return { priority: '0.75', changefreq: 'monthly' };
  if (DESTINATION_SLUGS.has(slug)) return { priority: '0.8', changefreq: 'monthly' };
  console.warn(`[sitemap] Unknown slug "${slug}" — defaulting to 0.8 / monthly. Add it to DESTINATION_SLUGS or SEO_LANDING_SLUGS in scripts/generate-sitemap.mjs`);
  return { priority: '0.8', changefreq: 'monthly' };
}

const files = fs
  .readdirSync(ROOT)
  .filter((f) => f.endsWith('.html') && f !== 'nav.html');

const slugs = [];
for (const f of files) {
  if (f === 'index.html') slugs.push('');
  else slugs.push(f.replace(/\.html$/, ''));
}

slugs.sort((a, b) => {
  if (a === '') return -1;
  if (b === '') return 1;
  return a.localeCompare(b);
});

let out = `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by scripts/generate-sitemap.mjs — run after adding a new public HTML page -->\n`;
out += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;

for (const slug of slugs) {
  const loc = slug === '' ? `${BASE}/` : `${BASE}/${slug}`;
  const { priority, changefreq } = priorityForSlug(slug);
  out += `  <url><loc>${loc}</loc><changefreq>${changefreq}</changefreq><priority>${priority}</priority></url>\n`;
}

out += `</urlset>\n`;

fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), out, 'utf8');
console.log(`Wrote sitemap.xml with ${slugs.length} URLs.`);
